Stabilize MavenDependencyUpdateTest
fixes #1067

the error was:
```
   1) Maven dependency update pom.xml on save test
       should invoke the update of the Maven dependencies when a step is
added:
     StaleElementReferenceError: stale element reference: stale element
not found in the current frame
  (Session info: chrome=134.0.6998.205)
      at Object.throwDecodedError
(node_modules/selenium-webdriver/lib/error.js:523:15)
      at parseHttpResponse
(node_modules/selenium-webdriver/lib/http.js:524:13)
      at Executor.execute
(node_modules/selenium-webdriver/lib/http.js:456:28)
      at process.processTicksAndRejections
(node:internal/process/task_queues:105:5)
      at async Driver.execute
(node_modules/selenium-webdriver/lib/webdriver.js:745:17)
      at async CenterNotification.getMessage
(node_modules/@redhat-developer/page-objects/out/components/workbench/Notification.js:43:23)
      at async /Users/runner/work/vscode-kaoto/vscode-kaoto/out/MavenDependencyUpdate.test.js:80:90
      at async Promise.all (index 0)
      at async /Users/runner/work/vscode-kaoto/vscode-kaoto/out/MavenDependencyUpdate.test.js:80:30
```

Signed-off-by: Aurélien Pupier <apupier@ibm.com>